server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route pour le service d'authentification
        - id: auth-service
          uri: http://servicerest2:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /session/$\{segment}

        # Route pour le service de bibliothèque
        - id: library-service
          uri: http://servicerest1:8080
          predicates:
            - Path=/api/library/**
          filters:
            - RewritePath=/api/library/(?<segment>.*), /$\{segment}

  session:
    store-type: redis
  
  redis:
    host: redis
    port: 6379

logging:
  level:
    org.springframework.cloud.gateway: DEBUG